version: '3.7'

services:

  econtriver-dev:
    container_name: econtriver-dev
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    ports:
      - 3001:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

  econtriver-prod:
    container_name: econtriver-prod
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:80'
    environment:
      - VIRTUAL_HOST=econtriver.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=econtriver.com
      - LETSENCRYPT_EMAIL=nik@econtriver.com
    restart: always

  nginx-proxy:
    container_name: nginx-proxy
    profiles:
      - prod
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    container_name: letsencrypt
    profiles:
      - prod
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

volumes:
  vhost:
  html:
  certs:
  dhparam:
  acme:
  conf:

networks:
  default:
    name: nginx-proxy
